### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by noahhaon** [NotVaryClever/tomato-nvram#2]
Hi,

I'm getting this error when trying to run tomato-nvram.py:

```
Traceback (most recent call last):
  File "./tomato-nvram.py", line 416, in <module>
    main(sys.argv[1:])
  File "./tomato-nvram.py", line 402, in main
    config = Config(args.config)
  File "./tomato-nvram.py", line 362, in __init__
    self.names, patterns = zip(*((name, section['pattern']) for name, section in parser.items() if 'pattern' in section))
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by noahhaon** [comment]
Was missing config.ini 🙈
